# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Relatable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ZLSwipeableViewSwift'
  pod "NextLevel", "~> 0.16.3"
  pod 'UIColor+FlatColors'

end
